# Generated by Django 4.2.16 on 2024-11-28 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project_board.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('authorised_editors', models.ManyToManyField(blank=True, related_name='authorised_editor', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(project_board.models.dud_user), to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveBigIntegerField(choices=[(0, 'Backlog'), (1, 'Todo'), (2, 'In Progress'), (3, 'Done')], default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=models.SET(project_board.models.dud_user), to=settings.AUTH_USER_MODEL)),
                ('project_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_board.project')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.TextField()),
                ('essay', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project_notes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_board.project')),
            ],
        ),
    ]
