# Generated by Django 4.2.16 on 2024-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='authorised_editors',
            new_name='authorised_editor',
        ),
    ]
