# Generated by Django 4.2.16 on 2024-11-28 20:19

from django.conf import settings
from django.db import migrations, models
import project_board.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='project',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(project_board.models.dud_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
