# Generated by Django 4.2.16 on 2024-11-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_tasks',
            new_name='associated_project',
        ),
    ]
