# Generated by Django 4.2.16 on 2024-12-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0002_rename_authorised_editors_project_authorised_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='taskTitle',
        ),
    ]
