# Generated by Django 4.2.16 on 2024-11-28 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_board', '0002_alter_project_last_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allowed_editors',
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_editors',
            field=models.ManyToManyField(blank=True, related_name='authorised_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
