# Generated by Django 4.2.16 on 2024-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0003_rename_title_task_tasktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=180),
        ),
    ]
