# Generated by Django 4.2.16 on 2024-11-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0004_remove_note_id_alter_note_notes_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Notes for',
            new_name='project',
        ),
    ]
