# Generated by Django 4.2.16 on 2024-11-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0005_rename_notes_for_note_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='project',
            new_name='Notes for',
        ),
    ]
